server:
  port: 88
spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: test_route1
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu
        - id: test_route2
          uri: https://www.qq.com
          predicates:
            - Query=url, qq
        #精确匹配的路由放在模糊匹配之前
        - id: product_route
          uri: lb://gulimall-product:10000
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        - id: admin_route
          uri: lb://renren-fast:8080
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}
## 前端项目 /api/，http://localhost:88/api/captcha.jpg  http://localhost:8080/renren-fast/captcha.jpg
